### ISSUE TITLE
Muzei Support

### ISSUE THREAD

**Issue by Kennyc1012** [Kennyc1012/Opengur#107]

**Comment by Jawnnypoo** [comment]
I was just thinking this would be a great thing to have. I recently did this on the Voat app I am working on if you want to take a look.

https://github.com/Jawnnypoo/voat-android

 Although, I really just followed the 500px example. Let me know if you want any help.

**Comment by Kennyc1012** [comment]
Its pretty much all finishing, there are a few little thing left to do but the bulk of the work is done. You can see it on the muzei branch. 

![device-2015-06-22-073749](https://cloud.githubusercontent.com/assets/2333025/8281023/bfa6710e-18b1-11e5-8a5a-cbaaf3adc55f.png)
![device-2015-06-22-073807](https://cloud.githubusercontent.com/assets/2333025/8281024/bfa8fa82-18b1-11e5-974b-7adbfb5fcd04.png)
