### ISSUE TITLE
Organize the code 

### ISSUE THREAD

**Issue by ppamorim** [Kennyc1012/Opengur#119]
Please, we need a better code for this, seriously. I'll do it for you.

**Comment by Kennyc1012** [comment]
What do you want more organized, give me some examples as all the classes are organized fairely well.

**Comment by ppamorim** [comment]
https://github.com/ppamorim/Amazing-MVP

It's a sample (outdated), I'm refactoring the code for you. But now I need return to my project. I'll work in my fork soon.

**Comment by Kennyc1012** [comment]
Be aware that a lot of the code base is about to change in the next week or so when the api_rewrite branch is merged into development

**Comment by ppamorim** [comment]
No problem my friend :)

**Comment by ppamorim** [comment]
We need to separate the API from the UI and domain. Can you do it?

**Comment by Kennyc1012** [comment]
Looking at your example, I rather stay away from this. I'm not a fan of Dagger and abstracting everything out seems to much work and I wouldn't want to have to relearn the entire code base for this.

**Comment by ppamorim** [comment]
man, It isn't hard. This makes your code more simple and readable. 
It's a excellent app, but we need to make it better.
