### ISSUE TITLE
Sharing of album link is buggy after viewing image

### ISSUE THREAD

**Issue by twig** [Kennyc1012/Opengur#120]
Steps to reproduce:

* Open up an album
* Click share to (whatever app that lets you see the URL)
* Take note of URL (it's right)
* Close sharing appp, go back to view album
* Open first image
* Press back to album view
* Press share button again
* This time the URL will be of the image, not the album

**Comment by Kennyc1012** [comment]
By opening an album, are you referring to open an album link (http://imgur.com/a/zrp2G) or opening a gallery post which is an album (http://imgur.com/gallery/zrp2G)

**Comment by twig** [comment]
Good question, I didn't realise there was a difference. I just checked again and it's a gallery post ([this one](https://imgur.com/gallery/RjtIz) to be exact)

**Comment by Kennyc1012** [comment]
I'm not seeing a different url, both times I am getting https://imgur.com/gallery/Rjtlz.

**Comment by twig** [comment]
Currently using 2.9.0. If it helps, here's that I did in [screenshot format](http://imgur.com/a/SQ2Va)

**Comment by Kennyc1012** [comment]
That is most likely the issue. I'm assuming you are on a devices that is running either 4.0 or 4.1 as with the 3.0 release, they were dropped as the app is only 4.2+ now. Here is the commit that updates the share intent https://github.com/Kennyc1012/Opengur/commit/659aebda42eff518b49299fe77cda72eeb9a1c4b.

**Comment by twig** [comment]
Ahh damn I'm on 4.1!

Thanks for the quick response

**Comment by Kennyc1012** [comment]
I upped the min version due to the older versions having memory issues. [Here](https://drive.google.com/file/d/0B76YfpA-PixvbzlneTRCVDQ0NGM/view?usp=sharing) is an apk of the latest release that will work on 4.1

**Comment by twig** [comment]
Oh dude this is amazing, animations are slick and runs much quicker!

Wow thanks so much for that!

Out of curiosity, what memory problems? (Also an Android dev and wondering if it affects my apps)

**Comment by Kennyc1012** [comment]
Mostly when viewing images full screen as the images get loaded at full res, nothing major.

**Comment by twig** [comment]
Ahh ok.

Thanks again Kenny, much appreciated!
