### ISSUE TITLE
Link to gallery in the "Share menu" is wrong

### ISSUE THREAD

**Issue by LeavOA** [Kennyc1012/Opengur#138]
1. uploaded images
2. "Shared" the gallery to "Reddit is fun" to submit to reddit
3. link shared was https://imgur.com/gallery/BlCW7
4. link should be https://imgur.com/a/BlCW7

**Comment by LeavOA** [comment]
(Also thanks for the awesome app... :)

**Comment by Kennyc1012** [comment]
When uploading, did you select upload submit to Imgur? Also, how did you "Share" the link?

**Comment by LeavOA** [comment]
Did not select submit to imgur.

Clicked on uploads in the left hand side menu, then clicked the album showing the three pictures (it had an icon of a picture on a picture in the upper right hand side)

Then used the share button on the upper right hand side.

**Comment by Kennyc1012** [comment]
Okay, confirmed bug. To work around this, when on the uploads screen, you can long press on the album thumbnail and select share/copy which will produce the correct link.
