### ISSUE TITLE
"client_id and response_type are required"

### ISSUE THREAD

**Issue by richardg867** [Kennyc1012/Opengur#145]
After logging in to Opengur using Imgur's Twitter login, I get the following error:

![](http://i.imgur.com/RLAnxd1.png)

If I back out of it and try logging in again, I get logged in instantly, and Opengur works without any issue.

**Comment by Kennyc1012** [comment]
This is most likely an issue on Imgurs side. I do not control anything with the login page, it is a webpage served by Imgur. Most likely their client_id isn't being served correctly when it first loads, but then works (somehow?) when you reload the page.

**Comment by Kennyc1012** [comment]
Another workaround I find to work is unistalling/reinstalling the app.
