### ISSUE TITLE
Upload the app to f-droid

### ISSUE THREAD

**Issue by l3d00m** [Kennyc1012/Opengur#146]
Is there a reason why it isn't on f droid?

**Comment by Kennyc1012** [comment]
I'm lazy and don't want to be bothered.

**Comment by tslocum** [comment]
@Kennyc1012 would you be opposed to someone submitting the app for you?  I've already submitted one of my apps to F-Droid and wouldn't mind taking care of the submission process for Opengur.  It's proven very useful by the way, thanks for providing an alternative to the ever-worsening official app.

**Comment by Kennyc1012** [comment]
@tslocum I briefly looked into it and it seems that because it uses Fabric/Crashlytics, it wouldn't be possible, but I might be wrong. If you're willing to do it, go for it.
