### ISSUE TITLE
Cannot login into account if captcha required

### ISSUE THREAD

**Issue by ramenchef** [Kennyc1012/Opengur#148]
I cannot hit the allow button when I try to log into my imgur account if a captcha is required.The ToS blurb covers the deny/allow buttons and I cannot click the allow button no matter how hard I try.
http://imgur.com/FtBEzUm

device is a nexus 5 on 5.1.1 stock.

**Comment by Kennyc1012** [comment]
There is nothing I can do about this as Imgur serves the webpage, its their rendering problems. I would suggest trying to login on a desktop, or in a browser app, then trying again in Opengur.
