### ISSUE TITLE
Zoom stops too soon

### ISSUE THREAD

**Issue by WazWaz** [Kennyc1012/Opengur#154]
Seems to stop at 1:1 pixels, which is way too small on very high resolution displays.

**Comment by Kennyc1012** [comment]
The way the image zoom works is decodes sections of the image instead of the full image. If the image is smaller than the device resolution, it will not need to decode and there for not have any zoom, this is working as intended.

**Comment by dilirst** [comment]
Perhaps a different decoder would be good. If you try Reddit Is Fun you can see the zoom allows for much deeper zoom. This is very useful very often, and forces many people to continue using RiF's built-in image viewer. In addition, it allows for zooming in on GIFs, which is awesome, but I suppose that deserves its own feature request post.
