### ISSUE TITLE
Login with non-imgur account

### ISSUE THREAD

**Issue by TheZoq2** [Kennyc1012/Opengur#169]
I use my google account to log into imgur but that option doesn't seem to work in opengur.

If I click the tap to login button in the sidebar, I get taken to a regular imgur login page but clicking on any of the "allow access with:" buttons doesn't do anything. The button click effect is shown but I remain on the imgur login site.

**Comment by Kennyc1012** [comment]
To login with a third party account, go to the login page and with the user name and password fields empty, select whatever third party you want to use and click allow. You will then go through the normal login flow on whatever site and be redirected back once logged in. See below gif

![login](https://cloud.githubusercontent.com/assets/2333025/14565672/2c3e4d40-02fa-11e6-9369-24091941e88b.gif)

**Comment by TheZoq2** [comment]
Ok that worked. Perhaps you should add something to tell users that because
it' not that obvious.
