### ISSUE TITLE
Load images over https

### ISSUE THREAD

**Issue by thefinn93** [Kennyc1012/Opengur#172]
It looks like images are loading over http. They should be loaded over https.

**Comment by Kennyc1012** [comment]
That is what the API responds with, making them HTTPS might cause some links to not work correctly. This is really an Imgur bug. 

`   {
            "id": "MRPxja9",
            "title": "What a mess",
            "description": null,
            "datetime": 1461253842,
            "type": "image/gif",
            "animated": true,
            "width": 960,
            "height": 540,
            "size": 9120948,
            "views": 40824,
            "bandwidth": 372353581152,
            "vote": null,
            "favorite": false,
            "nsfw": false,
            "section": "funny",
            "account_url": null,
            "account_id": null,
            "in_gallery": false,
            "gifv": "http://i.imgur.com/MRPxja9.gifv",
            "webm": "http://i.imgur.com/MRPxja9.webm",
            "mp4": "http://i.imgur.com/MRPxja9.mp4",
            "mp4_size": "536120",
            "webm_size": "334204",
            "link": "http://i.imgur.com/MRPxja9.gif",
            "looping": true,
            "comment_count": null,
            "ups": null,
            "downs": null,
            "points": null,
            "score": 34508,
            "is_album": false
        }`

**Comment by thefinn93** [comment]
Oh, that blows :(

**Comment by The0x539** [comment]
What kind of links would this break?

**Comment by eligrey** [comment]
@Kennyc1012 I manually convert all imgur links to https in my Android app and I never have any issues for any links. imgur has a proper TLS setup, so do not be afraid to make use of it.

**Comment by Kennyc1012** [comment]
I'll take a look into this
