### ISSUE TITLE
Switch to standard structure

### ISSUE THREAD

**Issue by Jawnnypoo** [Kennyc1012/Opengur#178]
This repo does not follow the typical structure of an Android app project, where you have the app contained within a module. I could forsee that if you ever wanted to do something like potentially create a wearable app or Android TV app, you would have to refactor the project. If you want, I can make a PR that restructures the app into a module, just wanted to first see if there was a reason for this structure.

**Comment by Kennyc1012** [comment]
Sure, wouldn't be opposed to it.
