### ISSUE TITLE
unable to open link

### ISSUE THREAD

**Issue by xtj-9182** [Kennyc1012/Opengur#183]
I was browsing reddit via reddit is fun when I stumbled upon a link that opengur was unable to open.

this is the imgur link: http://imgur.com/topic/Awesome/gBmRnF7

Here is the reddit thread:
https://www.reddit.com/r/funny/comments/4raobm/who_says_good_cosplay_needs_boobs/

**Comment by Kennyc1012** [comment]
Added to the never ending URL schemes of Imgur.
