### ISSUE TITLE
Subreddits not updating

### ISSUE THREAD

**Issue by boostedhp** [Kennyc1012/Opengur#184]
6 days ago all sub reddits stopped syncing with the actual sub. Opengur shows no new posts since then in active subs.

Have done the basics to resolve issue but it's persisting through force closing app, cleared cache, restarted phone. Is there any info that would be helpful?

**Comment by Kennyc1012** [comment]
I am seeing the same thing, but not sure if its an issue with the app. The app displays whatever the API responds with. If the API is giving old data, then I believe this to be an issue with Imgur and not the app. Will continue to look into it.

**Comment by Kennyc1012** [comment]
Confirmed this is an issue with Imgur. Even on their own site, the info is 6-7 days behind.
