### ISSUE TITLE
FDroid Repo

### ISSUE THREAD

**Issue by Ullarah** [Kennyc1012/Opengur#192]
Hi there!

Have you at some stage considered to put this on the FDroid repo?

If not, would it be okay to submit this wonderful app of yours?

Thanks! :+1:

**Comment by Kennyc1012** [comment]
Sure, go ahead. There is the f_droid flavor which does not include fabric.

**Comment by IzzySoft** [comment]
As it's still not there: Would you mind attaching the `.apk` to the corresponding `releases/` tag? I could pick it then from there automatically to include it with [my F-Droid compatible repo](https://android.izzysoft.de/repo). As soon as it turns up in the official repo, I can of course remove it again from mine to avoid confusion (mainly concerning the signature, as F-Droid signs itself).

**Comment by Kennyc1012** [comment]
Attached to the release

**Comment by IzzySoft** [comment]
Thanks, Kenny! [Added](https://apt.izzysoft.de/fdroid/index/apk/com.kennyc.open.imgur). Will you keep it up for the next releases? Please let the file have the `.apk` extension then, so my updater finds it :) No need to rename the current one (at least not from my end), as I've already picked it manually.

**Comment by Kennyc1012** [comment]
I haven't had as much time to work on this, if I release any other versions I will keep it up to date for f droid as well.

**Comment by IzzySoft** [comment]
Thanks again! As I wrote: As long as it's attached to the "latest version" and carries the `.apk` extension, my auto-updater will pick it up then.

@Ullarah feel free to add my repo to your F-Droid client meanwhile :)
