### ISSUE TITLE
Allow notifications to be sorted "most recent first"

### ISSUE THREAD

**Issue by wyatt8740** [Kennyc1012/Opengur#196]
I have thousands of old notifications in Opengur and don't like to delete them for posterity's sake. An option to sort notifications in reverse-order (or even a desktop-style 'scrollbar' to quickly jump to the bottom instead of swiping for five minutes) would be greatly appreciated.

**Comment by Kennyc1012** [comment]
This is currently not possible due to limitations with Imgur's API

**Comment by wyatt8740** [comment]
@Kennyc1012 Hm, okay. Maybe if we looked at the javascript the proper website uses we could implement it, though?

If I remember, I'll give it a shot.
