### ISSUE TITLE
Ability to choose app accent colour (instead of it being coupled to the app colour theme)

### ISSUE THREAD

**Issue by wopian** [Kennyc1012/Opengur#88]
Could there be a second drop down underneath the theme colour to choose which colour you want the accent colour to be?

At the moment all the app theme colours have their own different accent colour for header text, check boxes and the FAB. While on some themes they go together great, others they're a real *eyesore* when put together - such as the Pink theme with the bright blue accent colour for example:

![](http://i.imgur.com/4upnyk4.png)
![](http://i.imgur.com/vJY692v.png)
![](http://i.imgur.com/zgJvotK.png)

**Comment by Kennyc1012** [comment]
I rather avoid this as the accent colors need to be specific to the primary
colors so there isn't clashing anywhere, such as pop ups when selecting a
comment. If you have a suggestion for updated colors or a new theme I'd be
willing to put them in if they are acceptable.

**Comment by Kennyc1012** [comment]
I rather avoid this as the accent colors need to be specific to the primary
colors so there isn't clashing anywhere, such as pop ups when selecting a
comment. If you have a suggestion for updated colors or a new theme I'd be
willing to put them in if they are acceptable.
