### ISSUE TITLE
Comment Text Suggestions

### ISSUE THREAD

**Issue by pieter3d** [Kennyc1012/Opengur#94]
When typing a new comment, the text field disables next word prediction for the Google keyboard. On Android 5.1.1

**Comment by Kennyc1012** [comment]
This is intentional. There is a bug in android that causes an EditText to leak a context when using text suggestions http://stackoverflow.com/questions/8497965/why-does-edittext-retain-its-activitys-context-in-ice-cream-sandwich .

**Comment by pieter3d** [comment]
Ah, maybe that can be done only to affected versions? Kind of miss the
spell checking!

**Comment by Kennyc1012** [comment]
Its on devices 4.0+, so every device supported :/ . I'll see if I can find a work around to it though

**Comment by pieter3d** [comment]
Ok that'd be great. The reddit is fun app seems to be able to handle this
for example (or maybe they just let the leak happen?)
