### ISSUE TITLE
Pop-up comment images are too small

### ISSUE THREAD

**Issue by pieter3d** [Kennyc1012/Opengur#98]
It appears that when tapping a image url in a comment, it is loaded and drawn at native resolution. On high dpi phones that means they are often tiny, like 10x10mm. Would be nice if it just scaled up until it reaches the edge of the screen

**Comment by Kennyc1012** [comment]
The images loaded from comments are displayed at their actual sizes. So if they are really small, they will appear small. Tap on them in the popup to open them full screen which will make them larger.

**Comment by pieter3d** [comment]
Yes I  noticed that option. Just a weird extra step

**Comment by Kennyc1012** [comment]
Its a limitation of the dialog fragments, I rather avoid hacking them to make them larger.

**Comment by pieter3d** [comment]
Ah ok. I appreciate your responsiveness :)
